name: advance_pdf_viewer2
description: A fork from a flutter plugin for handling PDF files. Works on both Android, iOS and macOS
version: 2.0.5
homepage: https://github.com/lohanidamodar/pdf_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  numberpicker: ^2.1.1
  path_provider: ^2.0.8

dev_dependencies:
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
      macos:
        pluginClass: FlutterPluginPdfViewerPlugin
