name: advance_pdf_viewer2
description: A fork from a flutter plugin for handling PDF files. Works on both Android, iOS ( MacOS and Web are under testing )
version: 2.0.6-beta.2
homepage: https://github.com/lohanidamodar/pdf_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  numberpicker: ^2.1.2
  path_provider: ^2.1.1
  pdfx: any

dev_dependencies:
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
        fileName: advance_pdf_viewer.dart
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
        fileName: advance_pdf_viewer.dart
      macos:
        pluginClass: FlutterPluginPdfViewerPlugin
        fileName: advance_pdf_viewer.dart
